FROM node:16
# WORKDIR /usr
COPY package.json ./
COPY tsconfig.json ./
COPY src ./src
RUN ls -a
RUN npm install -g npm
RUN npm install -g typescript
RUN npm install
EXPOSE 4000
CMD ["npm","run","ts:node"]